Add search function to send message to every contact(even if at last) and add ability to choose FireFox or Chrome driver
mrpandya/whatsapp-bomber pull request #17
Opened 2022-10-02 18:41 UTC by IamMU

# List Of Changes:
 - Fix issue #6 (Working and tested a lot)
 - Fix issue #5 (Not fully tested)
# Additional Libraries:
 - None

2022-10-02 19:04 UTC, mrpandya commented on whatsappbomber.py
> +                time.sleep(0.4)
why do we need time.sleep()?

2022-10-02 19:07 UTC, mrpandya commented on whatsappbomber.py
> +                # send_button = wait.until(EC.presence_of_element_located(("xpath", "/html/body/div[1]/div/div/div[4]/div/footer/div[1]/div/span[2]/div/div[2]/div[2]/button")))
remove unnecessary comments

2022-10-02 19:12 UTC, mrpandya requested changes
please remove unnecessary comments and also we do not need the log file to be in our repo.
along with this do mention in the readme that the user has to add the geckodriver in the folder or else upload the geckodriver and create a new PR. I'd suggest you upload the geckodriver just like you uploaded the chromium driver. Also I didn't notice that there was already a chromedriver in the repo so if possible remove the older version and make another PR regarding the same, I will add the hacktoberfest-accepted label for the same.

2022-10-02 19:25 UTC, IamMU commented on whatsappbomber.py
> +                # send_button = wait.until(EC.presence_of_element_located(("xpath", "/html/body/div[1]/div/div/div[4]/div/footer/div[1]/div/span[2]/div/div[2]/div[2]/button")))
Done

2022-10-02 19:25 UTC, IamMU commented
I'll upload the driver to the same pr

2022-10-02 19:30 UTC, IamMU commented
See if all files are there. I put the geckodriver and a new version of chromedriver in the commit

2022-10-04 08:09 UTC, mrpandya approved these changes

2022-10-04 08:09 UTC, merged